### PR TITLE
added a tooltip to every device

### PR DESCRIPTION
**Pull request by Arlon1**

### CODE REVIEW

**Comment by chriscamacho** [comment]
why are you replacing a dialog with a label the tooltip is okay, but not understanding the second unrelated change bundled with this pull request.

**Comment by Arlon1** [comment]
The secound commit was not intended to be pushed (yet).
I only wanted to do a pull request about the tooltip.
Sorry about that.

**Comment by chriscamacho** [comment]
okay should I close this one so you can make another, probably better to separate those out anyhow, thanks

**Comment by Arlon1** [comment]
Let's use this request for the tooltip. Now there should be only displayed changes dealing with the tooltip.

**Comment by chriscamacho** [comment]
yes lets! - thanks...

**Pull request merged**
